ingress:
  host: buildmystudy.com
  pathType: Prefix

service:
  port: 80

spring:
  labels: survey
  image:
    repository: # ECR에 저장된 스프링 이미지 URL
    tag: latest
  service:
    port: 80
    survey:
      name: survey-service
      port: 8083
  datasource:
    url: ""
    username: ""
    password: ""

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage : 75

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75

  behavior:
    scaleUp:
      stabilizationWindowSeconds: 120
      policies:
        - type: Percent
          value: 100
          periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 10
          periodSeconds: 60
        - type: Pods
          value: 1
          periodSeconds: 60
